---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kan-kafka-1
  labels:
    app: kan-kafka
    kanBrokerId: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kan-kafka
      kanBrokerId: "1"
  template:
    metadata:
      labels:
        app: kan-kafka
        kanBrokerId: "1"
    spec:
      hostname: kafka-1
      subdomain: kan-kafka
      containers:
      - name: kafka
        image: kafkanetes/minikan-kafka:0.1.0_2.13_2.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: kan-zk:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kan-kafka:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://kafka-1.kan-kafka:9092
