---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kan-kafka-socat-1
  labels:
    app: kan-socat
    os: alpine 
    forwards: kafka
    kanBrokerId: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kan-socat
      os: alpine 
      forwards: kafka
      kanBrokerId: "1"
  template:
    metadata:
      labels:
        app: kan-socat
        os: alpine 
        forwards: kafka
        kanBrokerId: "1"
    spec:
      containers:
        - name: socat
          image: alpine/socat:1.7.3.4-r0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9092
          args: ["tcp-l:9092,fork,reuseaddr", "tcp:kan-kafka-1:9092"]
---
apiVersion: v1
kind: Service
metadata:
  name: kan-kafka-socat-1
  labels:
    app: kan-socat
    os: alpine
    forwards: kafka
    kanBrokerId: "1"
spec:
  type: ClusterIP
  ports:
  - name: socat-kafka-port
    port: 9092
    protocol: TCP
  selector:
    app: kan-socat
    os: alpine
    forwards: kafka
    kanBrokerId: "1"
